#!/bin/sh
 
### BEGIN INIT INFO
# Provides:          tomcat
# Short-Description: Start and stop Apache Tomcat
# Description:       Enable Apache Tomcat service provided by daemon.
### END INIT INFO

ECHO=/bin/echo
TOMCAT_USER=tomcats
TOMCAT_HOME=/opt/apache-tomcat-8.5.9
TOMCAT_START_SCRIPT=$TOMCAT_HOME/bin/startup.sh
TOMCAT_STOP_SCRIPT=$TOMCAT_HOME/bin/shutdown.sh
 
if [ $(id -u) != 0 ]; then
   $ECHO "You must be root or have sudo privileges!!"
   exit 1
fi
start() {
	$ECHO -n "Starting Tomcat"
	su $TOMCAT_USER -s /bin/bash -c "$TOMCAT_START_SCRIPT"
} 
stop() {
	$ECHO -n "Stopping Tomcat"
	su $TOMCAT_USER -s /bin/bash -c "$TOMCAT_STOP_SCRIPT &"
	while [ "$(ps -fu $TOMCAT_USER | grep java | grep tomcat | wc -l)" -gt "0" ]; do
		sleep 5; $ECHO -n "."
	done
}
status() {
	if [ $(ps -efa | grep java | grep tomcat -c) -gt 0 ]; then
	$ECHO "Tomcat is running"
	else
	$ECHO "Tomcat is not running"
	fi	 	
}
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	status)
		status
		;;
	restart)
		stop
		sleep 30
		start
		;;
	*)
		$ECHO "Usage: tomcat {start|stop|restart|status}"
		exit 1
esac
exit 0
