---
- name: Customise banner and prompt
  hosts: all_vm
  tasks:
  - name: Modify main banner
    become: yes
    become_user: root
    copy: backup=yes src=motd dest=/etc/ owner=root group=root mode=0644
  - name: Customise PS1 on bashrc for the user who is running this
    blockinfile:
     dest: /home/sorea/.bashrc
     block: |
       #Font color
       #red=$(tput setaf 1)
       #green=$(tput setaf 2)
       #yellow=$(tput setaf 3)
       #blue=$(tput setaf 4)
       #purple=$(tput setaf 5)
       #cyan=$(tput setaf 6)
       #white=$(tput setaf 7)
       #Background color
       #blueF=$(tput setab 4)
       #grayF=$(tput setab 7)
       #Backgrounf no color
       #sc=$(tput sgr0)
       PS1='\[$(tput setaf 2)\]\u\[$(tput setaf 7)\]@\[$(tput setaf 1)\]\h\[$(tput setaf 9)\]$(IFS=/ d=($PWD); IFS=\n c={{ '${#d[@]}' }}; if [[ $PWD == $HOME ]]; then echo "~"; elif [ $c -gt 5 ]; then echo "/${d[1]}/${d[2]}/.../${d[$c-2]}/${d[$c-1]}"; else echo $PWD; fi)\[$(tput setaf 7)\]\$ \[$(tput setaf 7)\]'
